export const SELECT_BANK = "SELECT_BANK";
export const POWER_ON_OFF = "POWER_ON_OFF";
export const DRUM_PAD_CLICKED = "DRUM_PAD_CLICKED";
export const VOLUME_CHANGE = "VOLUME_CHANGE";
export const SET_VOLUME_INTERVAL = "SET_VOLUME_INTERVAL"